name: Publish
on: [push]
jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: clean some files
        run: rm -rf .git/ .github/ .gitignore README.md build.cmd

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: sync
          source: ./
          destination: s3://mx-5/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-3
